# Generated by Django 4.2.7 on 2025-05-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_rim'),
    ]

    operations = [
        migrations.CreateModel(
            name='RimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('brand', models.CharField(db_index=True, max_length=100, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='rims/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Модель диска',
                'verbose_name_plural': 'Модели дисков',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RimVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField(verbose_name='Диаметр')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('bolt_pattern', models.CharField(max_length=50, verbose_name='Тип крепления')),
                ('offset', models.CharField(blank=True, max_length=20, verbose_name='Вылет (ET)')),
                ('dia', models.CharField(blank=True, max_length=20, verbose_name='DIA')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('material', models.CharField(max_length=50, verbose_name='Материал')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rims/variants/', verbose_name='Изображение')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tyres.rimmodel')),
            ],
            options={
                'verbose_name': 'Вариант диска',
                'verbose_name_plural': 'Варианты дисков',
                'ordering': ['model__brand', 'model__name', 'diameter', 'width'],
            },
        ),
        migrations.DeleteModel(
            name='Rim',
        ),
        migrations.AddIndex(
            model_name='rimmodel',
            index=models.Index(fields=['brand', 'name'], name='tyres_rimmo_brand_a7d348_idx'),
        ),
        migrations.AddIndex(
            model_name='rimvariant',
            index=models.Index(fields=['diameter', 'width', 'bolt_pattern'], name='tyres_rimva_diamete_27acc7_idx'),
        ),
        migrations.AddIndex(
            model_name='rimvariant',
            index=models.Index(fields=['price'], name='tyres_rimva_price_c036e1_idx'),
        ),
    ]
