# Generated by Django 4.2.7 on 2025-05-20 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tyres', '0003_rimmodel_rimvariant_delete_rim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteRim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rim_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by_rims', to='tyres.rimvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_rims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rim_variant')},
            },
        ),
    ]
