# Generated by Django 4.2.7 on 2025-05-20 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0003_rimmodel_rimvariant_delete_rim_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tyres.rimvariant', verbose_name='Диск'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tyres.tyrevariant', verbose_name='Шина'),
        ),
    ]
